env:
  global:
    - secure: "C2q+hdZT5spjDC7mG5OL4nnJnxNzDzzWWSen3Y+QHbvb8Py9lZYZfRxplg357GgpYuwd649ZNDwp9QrQlsl13VegK/YDaJ67FOYJ/JFUgsLAX7JqEVaMSf2NV7uTK+Nsp/Fj+BeBynQ3g1kS+M6mEVVSps1i3xdYEh8SM0SfG06ooSgF1ouhNr4C4r5JdFtVnAy2roH3EGTQWjZWDReGWky13I3Y/5dy+6r84RJp8+tPb4EGgZKSrl/w4V+NEbefeM6Ds/BecenutTrmBCYlRb4KH1AWcaJrNLhpbsyFHtQDw74o6LEbOf294H4yPMQx0N+5wEdb3f9VeY00nKulpK2hdtKU9ivqsjiIjtGn44YQWYJ3vaucJ8SLAjaHlzRLhMnBjNo9xHO6JtiHPy9/6M3ZdF1KLWHF0Du1Yc63GcaqLWkDHzkdJKyclw/e3tcbXMRoEPDaE1Dl2MVVuUsQk+uw8HEnM6tMMMCGAOze+5tslgSdgsS6tm2EzNvzzh2YKNPScyJfyMN6Rd8PQpYpLJex3VLO5SgU0j/YsKjDSW9ULfrDRKQjeF8CZodcxaMA+b07jf2oe2QvHDChTBfXinvSgSAfpEkGb7NHVRHdEnYeT1OapPJVa1sXSOZPfK8GtEiQijshQDKo035Xu5bcQBcZcKbN/VJqWYdNYdDNFt4="
    - secure: "Gpj1jKHRGz0tQCUanjIn7fpENhcvRrOEDcNJ8MENsBmAqU7ygQwFCYzMgoMwg4VFaE2s+baS/SR2bvivUl+Sz5Ravk9Ow102RmLrc/ybFi0cQy2Ums0nOoOtY6VMp9kubGuzZg384JQgiw3Xs9XtHukS15dkaGgnDUoZjdpKw9QyciQer+PGJS67Qwrz5IG0RSMDea9ya0sXc6ElHSZ9cXvK6VGlh8J533Jc0zMFZjmp6LFsdIEoAlVynQX6kkk9j1/d1C0BF1W8cRPS1yuDoVTSoUoh6HD48DImCJmreeMd2VkZRTY1PkF7iMiHuYLJOCjFySfTua7satJ39CXruVs0U3aDVnIukVjgGBkhFXUBYd45LvgfxVP93fBV2rg5yeAMoHZ6XU3voIWQ0tmsbiDYR7RYXDZotI6p4cIC+qm14lnzPoExjAacPcHHqsEDrLZ2Y+cmoxifR/1yDf3rQdqL8fJ2yIxJyNQvD3lrnicjGYl2BQjS+jtcECSWKIsj0YQ1LmlEwmuRW01E5qR1omf0IuAMKu9Br0KAtYUQYKwfKlth2Mc7n1fW3Ne4JGa4zRJdipQfMx5VKkd7PM0+CikufAybfSjw7FY1JQBYoXqDNbdxMla9t2OQQKpIomvjwvFfwE6QfN5zkiMd5a22sqQUX0XjjbZzcHV0z+pRNcc="
    - secure: "ZVXmzbTsZR9gyDJC1FQofu7+7aHb7gWHgt1S1FX9u1GbcJBsBhJLtBjRLLN7NhbWeuEJxAFY5vrKjIGbJhj3ZStVsHeZ94OAAG0GGxjgF03MkTRjwfSVCqbU0xupNurpsu8j6YjWzki1Xv0B79OE1cepBqziXZUFWutGeNAGLUFr74+QtbS6ieHiFp10m3nkjbVIy+nh/dlCs1w1LDyeIRZpL2PJcui1OMI5oaS8bvIk0LUpPy2kEbPeP+3JKYBzHhcoJQfT5w1AXGsSjgp3TTPLNblhZOt1EGNY5451hTl37tviRkxAnduxyvcWLKPKsDxt/ZKjUXj9cezBywHWbFYJTbBqHMNxgsv6oBfWT/ioIdxmuHV26/XTbd+PkubH/cIKWdz9qHeC6dSMU/JuzieheiTTj4HwsEOBtXiKuFDR5AK6CSGf4sPQdORhaqLzYADZQGjAstBMm66fbUSOw+EqS2F7kX2N96ecyZzmqti/YGl+xMH563DfnecRLfzWcc08rJWAnzD8GY4zcLSH2bwqnq1G0GmFMQ3F82ombTFCirs4T/ICyhLpnxyrHvEXa1Kr3IYuK3u54o9E2hP1wnZNHl4oJPSux9DR/GPgbOA6WNKcY0q7ePuXX3AuHX0WyW11i7jB7L+nxaXyGTDjTqjKZciiDCBhxmKUIbE1szE="

jobs:
  include:
    - stage: deploy
      if: type != pull_request
      name: PyPI upload 

      os: linux
      dist: xenial
      language: python
      python: 3.7
      
      install: 
        - pip3 install twine

      script:
        - if [[ $TRAVIS_REPO_SLUG = 'colomoto/pyMaBoSS' && $TRAVIS_TAG != '' ]]; then
            python setup.py sdist;
            twine upload -u __token__ -p $PYPI_UPLOAD_TOKEN dist/*;
          
          fi
