{% set name = "pyMaBoSS" %}
{% set version = "0.8.11" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ..

channels:
  - colomoto

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - colomoto_jupyter >=0.4.10
    - maboss >=2.6.0
    - pandas
    - pyparsing
    - python
    - matplotlib
    - ipywidgets
    - scikit-learn
    - networkx
    - pygraphviz
    - cmaboss >=1.0.0b27

about:
  home: https://github.com/colomoto/pyMaBoSS
  summary: 'Python API for the MaBoSS simulation software'

